version: '3'
services:
  influxdb:
    image: influxdb:2.0
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb:/var/lib/influxdb2
    ports:
      - "8086:8086"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432
volumes:
  influxdb:
  postgres:
